name: CI/CD_Action
on:
  push:
    branches: ["main"]
jobs:
  build:
  
    runs-on: self-hosted
    steps:
    - name: checkhead
      run: |
           echo "Check Ok!!"
           echo "Action Will Run"
